services:
  typesense:
    image: typesense/typesense:28.0.rc10
    restart: on-failure
    ports:
      - '8108:8108'
    volumes:
      - ./tmp/typesense:/data
    command: '--data-dir /data --api-key=123 --enable-cors'
